service:
  name: solid-winner

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs8.10

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello

custom:
  serverless-offline:
    port: ${env:SERVERLESS_OFFLINE_PORT}
